// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsvD8kGtafl3feZEuuFFaAgrrhaZiE_Jc',
    appId: '1:186440999752:web:f7092e492d5a7f4184497d',
    messagingSenderId: '186440999752',
    projectId: 'lapakbantul-7ce0b',
    authDomain: 'lapakbantul-7ce0b.firebaseapp.com',
    storageBucket: 'lapakbantul-7ce0b.firebasestorage.app',
    measurementId: 'G-LKRNCTTFVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAURhIV1CNY7QnD0n5rGtYm3nplQOa2pwM',
    appId: '1:186440999752:android:1ea1b7b5da99dcb484497d',
    messagingSenderId: '186440999752',
    projectId: 'lapakbantul-7ce0b',
    storageBucket: 'lapakbantul-7ce0b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsvD8kGtafl3feZEuuFFaAgrrhaZiE_Jc',
    appId: '1:186440999752:web:723735251ea9d18e84497d',
    messagingSenderId: '186440999752',
    projectId: 'lapakbantul-7ce0b',
    authDomain: 'lapakbantul-7ce0b.firebaseapp.com',
    storageBucket: 'lapakbantul-7ce0b.firebasestorage.app',
    measurementId: 'G-L3D9VYSRG2',
  );
}
